# Generated by Django 4.0.5 on 2022-06-03 21:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nt_title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('nt_description', models.TextField(default='', max_length=3000, verbose_name='Текст')),
                ('nt_importance', models.BooleanField(default=False, verbose_name='Важно')),
                ('nt_public', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('nt_status', models.IntegerField(choices=[(2, 'Активна'), (1, 'Отложена'), (0, 'Выполена')], default=2, verbose_name='Статус задачи')),
                ('nt_createtime', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('nt_updatetime', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('nt_endtime', models.DateTimeField(default=datetime.datetime(2022, 6, 4, 21, 22, 36, 587132), verbose_name='Выполнить к:')),
                ('nt_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Заметка',
                'verbose_name_plural': 'Заметки',
                'ordering': ['nt_endtime'],
            },
        ),
    ]
